### ISSUE TITLE
Directory where to install this plugin

### ISSUE THREAD

**Issue by arieliten** [valentineus/moodle-webhooks#8]
Hi, I'm trying to install it into my server but I'm not sure where should I uncompress or clone the code here. I tried doing it under `{root}/repository` but it failed to install. Any idea? Thanks

**Comment by valentineus** [comment]
@arieliten Hi!
If you want to install the plug-in in Moodle manually, you need to clone the repository in the local plug-ins folder:

```bash
# Go to the local plugins directory
# Example: cd /var/www/moodle/local
cd /path/to/moodle/local

# Cloning the repository
git clone https://github.com/valentineus/moodle-webhooks.git webhooks
```

After that, Moodle the user with administrator rights will ask permission to install the plug-in.
