### ISSUE TITLE
Install.xml Path Incorrect

### ISSUE THREAD

**Issue by mlohoar** [valentineus/moodle-webhooks#9]
When I copied the files to the folder /local/webhooks I got an error at install saying that the path in install.xml was incorrect.  In the original the value is blocks/local_webhooks/db.

I changed this to local/webhooks/db  it still complained, but did create the table and completed the install.

is the value blocks/local_webhooks/db correct or had you created this folder seperately?

**Comment by valentineus** [comment]
Thank you for issue.
New version of Moodle uses strict checking of variable `PATH`.
Thank you for reporting, I did not encounter such a problem.
Fixed: [3fa97bad312f24b815eac5b374e321512bc6aa4a]
